//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalaryComponentAmount
    {
        public int SalaryComponentAmountID { get; set; }
        public int PaySlipID { get; set; }
        public int SalaryComponentID { get; set; }
        public Nullable<decimal> EmployeeAmount { get; set; }
        public Nullable<decimal> EmployerAmount { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
    
        public virtual SalaryComponent SalaryComponent { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual PaySlip PaySlip { get; set; }
    }
}
