//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDetail
    {
        public int UserDetailID { get; set; }
        public string UserID { get; set; }
        public int CompanyBranchID { get; set; }
        public string ProfilePic { get; set; }
        public string Gender { get; set; }
        public string AdhaarNumber { get; set; }
        public string PanNumber { get; set; }
        public string BankAccountNumber { get; set; }
        public string ProvidentFundNumber { get; set; }
        public string EsicNumber { get; set; }
        public System.DateTime DateOfBirth { get; set; }
    
        public virtual CompanyBranch CompanyBranch { get; set; }
        public virtual User User { get; set; }
    }
}
