//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLeave
    {
        public int UserLeaveID { get; set; }
        public string UserID { get; set; }
        public int LeaveTypeID { get; set; }
        public int NumberOfLeave { get; set; }
    
        public virtual LeaveType LeaveType { get; set; }
        public virtual User User { get; set; }
    }
}
